// <auto-generated />
using System;
using Bangboo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bangboo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bangboo.Models.AuthsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateOnly>("ExpiresIn")
                        .HasColumnType("date")
                        .HasColumnName("expires_in");

                    b.Property<decimal>("FkUserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("fk_user");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_type");

                    b.HasKey("Id");

                    b.HasIndex("FkUserId")
                        .IsUnique();

                    b.ToTable("auths");
                });

            modelBuilder.Entity("Bangboo.Models.GuildsModel", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<string>("Banner")
                        .HasColumnType("text")
                        .HasColumnName("banner");

                    b.Property<decimal>("FkOwnerId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("fk_owner");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<decimal?>("LogsChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("logs_channel_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("XpPerMessage")
                        .HasColumnType("bigint")
                        .HasColumnName("xp_per_message");

                    b.HasKey("Id");

                    b.HasIndex("FkOwnerId");

                    b.ToTable("guilds");
                });

            modelBuilder.Entity("Bangboo.Models.MemberEventsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BoostChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("boost_channel_id");

                    b.Property<decimal>("FkGuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("fk_guild_id");

                    b.Property<decimal?>("ModChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("mod_channel_id");

                    b.Property<bool>("OnBan")
                        .HasColumnType("boolean")
                        .HasColumnName("on_ban");

                    b.Property<bool>("OnBoost")
                        .HasColumnType("boolean")
                        .HasColumnName("on_boost");

                    b.Property<bool>("OnJoin")
                        .HasColumnType("boolean")
                        .HasColumnName("on_join");

                    b.Property<bool>("OnLeave")
                        .HasColumnType("boolean")
                        .HasColumnName("on_leave");

                    b.Property<bool>("OnMute")
                        .HasColumnType("boolean")
                        .HasColumnName("on_mute");

                    b.HasKey("Id");

                    b.HasIndex("FkGuildId")
                        .IsUnique();

                    b.ToTable("member_events");
                });

            modelBuilder.Entity("Bangboo.Models.MembersModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("FkGuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("fk_guild_id");

                    b.Property<decimal>("FkUserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("fk_user_id");

                    b.Property<decimal>("GuildModelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.HasIndex("FkUserId");

                    b.HasIndex("GuildModelId");

                    b.ToTable("members");
                });

            modelBuilder.Entity("Bangboo.Models.MousetrapsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<decimal>("FkGuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("fk_guild_id");

                    b.Property<string>("MessageDm")
                        .HasColumnType("text")
                        .HasColumnName("message_dm");

                    b.Property<bool>("ShouldBan")
                        .HasColumnType("boolean")
                        .HasColumnName("should_ban");

                    b.HasKey("Id");

                    b.HasIndex("FkGuildId")
                        .IsUnique();

                    b.ToTable("mousetraps");
                });

            modelBuilder.Entity("Bangboo.Models.SessionsModel", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<long>("FkAuthId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_auth_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("FkAuthId");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("Bangboo.Models.UsersModel", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Bangboo.Models.AuthsModel", b =>
                {
                    b.HasOne("Bangboo.Models.UsersModel", "UserModel")
                        .WithOne("AuthModel")
                        .HasForeignKey("Bangboo.Models.AuthsModel", "FkUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("Bangboo.Models.GuildsModel", b =>
                {
                    b.HasOne("Bangboo.Models.UsersModel", "UsersModel")
                        .WithMany("GuildsModel")
                        .HasForeignKey("FkOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsersModel");
                });

            modelBuilder.Entity("Bangboo.Models.MemberEventsModel", b =>
                {
                    b.HasOne("Bangboo.Models.GuildsModel", "GuildModel")
                        .WithOne("MemberEventModel")
                        .HasForeignKey("Bangboo.Models.MemberEventsModel", "FkGuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildModel");
                });

            modelBuilder.Entity("Bangboo.Models.MembersModel", b =>
                {
                    b.HasOne("Bangboo.Models.UsersModel", "UserModel")
                        .WithMany("MembersModel")
                        .HasForeignKey("FkUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangboo.Models.GuildsModel", "GuildModel")
                        .WithMany("MembersModel")
                        .HasForeignKey("GuildModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildModel");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("Bangboo.Models.MousetrapsModel", b =>
                {
                    b.HasOne("Bangboo.Models.GuildsModel", "GuildModel")
                        .WithOne("MousetrapsModel")
                        .HasForeignKey("Bangboo.Models.MousetrapsModel", "FkGuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildModel");
                });

            modelBuilder.Entity("Bangboo.Models.SessionsModel", b =>
                {
                    b.HasOne("Bangboo.Models.AuthsModel", "AuthModel")
                        .WithMany("SessionsModel")
                        .HasForeignKey("FkAuthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthModel");
                });

            modelBuilder.Entity("Bangboo.Models.AuthsModel", b =>
                {
                    b.Navigation("SessionsModel");
                });

            modelBuilder.Entity("Bangboo.Models.GuildsModel", b =>
                {
                    b.Navigation("MemberEventModel")
                        .IsRequired();

                    b.Navigation("MembersModel");

                    b.Navigation("MousetrapsModel")
                        .IsRequired();
                });

            modelBuilder.Entity("Bangboo.Models.UsersModel", b =>
                {
                    b.Navigation("AuthModel")
                        .IsRequired();

                    b.Navigation("GuildsModel");

                    b.Navigation("MembersModel");
                });
#pragma warning restore 612, 618
        }
    }
}
